export default function getlistaEquipos() {
  return [
    { value: "Ajax", label: "Ajax" },
    { value: "Alemania", label: "Alemania" },
    { value: "Argentina", label: "Argentina" },
    { value: "Arsenal", label: "Arsenal" },
    { value: "Atlético Madrid", label: "Atlético Madrid" },
    { value: "Barcelona", label: "Barcelona" },
    { value: "Bayern Munich", label: "Bayern Munich" },
    { value: "Bélgica", label: "Bélgica" },
    { value: "Borussia Dortmund", label: "Borussia Dortmund" },
    { value: "Brasil", label: "Brasil" },
    { value: "Chelsea", label: "Chelsea" },
    { value: "Chile", label: "Chile" },
    { value: "España", label: "España" },
    { value: "Francia", label: "Francia" },
    { value: "Holanda", label: "Holanda" },
    { value: "Inglaterra", label: "Inglaterra" },
    { value: "Inter", label: "Inter" },
    { value: "Italia", label: "Italia" },
    { value: "Juventus", label: "Juventus" },
    { value: "Lazio", label: "Lazio" },
    { value: "Liverpool", label: "Liverpool" },
    { value: "Lyon", label: "Lyon" },
    { value: "Manchester City", label: "Manchester City" },
    { value: "Manchester United", label: "Manchester United" },
    { value: "Milan", label: "Milan" },
    { value: "Mónaco", label: "Mónaco" },
    { value: "Nápoli", label: "Nápoli" },
    { value: "Porto", label: "Porto" },
    { value: "Portugal", label: "Portugal" },
    { value: "PSG", label: "PSG" },
    { value: "Real Madrid", label: "Real Madrid" },
    { value: "Roma", label: "Roma" },
    { value: "Sevilla", label: "Sevilla" },
    { value: "Tottenham", label: "Tottenham" },
    { value: "Uruguay", label: "Uruguay" },
  ];
}
